### ISSUE TITLE
Overwrite aborts regardless of input [Windows]

### ISSUE THREAD

**Issue by dehanj** [tillitis/tkey-sign-cli#20]
When using Windows and a file already exists, you get the option to overwrite it or not, regardless of input it is always aborted.

```
$ tkey-sign -S -m pubkey -p pubkey
File pubkey.sig exists. Overwrite [y/n]?
y
Aborted
```

tkey-sign v0.0.8

**Comment by mchack-work** [comment]
A workaround is, of course, to delete the pubkey.sig file and try again.

**Comment by dehanj** [comment]
Also present in v1.0.0
