### ISSUE TITLE
USS input fails on Windows

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tkey-sign-cli#26]
Using `tkey-sign -G -p key.pub --uss` fails with:

```
ReadPassword: The handle is invalid.
```

**Comment by dehanj** [comment]
Most likely related https://github.com/tillitis/tkeyutil/issues/4

**Comment by mchack-work** [comment]
So let's update tkeyutil here and do a new release of tkey-sign-cli. Will also include the fix on Windows for "y/n".
