### ISSUE TITLE
tkey-sign: Sign arbitratry long files

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tkey-sign-cli#5]
Make tkey-sign a bit more useful.

- [x] Embed `signer` and load automatically.
- [x ] Sign arbitrarily long files with `signer`. Probably by using a hash over the file and signing that instead of the file data. Perhaps hide this functionality behind a flag.

Probably needs to use ed25519-ph for pre-hash signatures from Monocypher 4, so update Monocypher first.

**Comment by mchack-work** [comment]
Please see https://github.com/tillitis/tkey-sign-cli/pull/6

**Comment by dehanj** [comment]
#6 merged.
